from app.schemas.trip import (
    AccommodationSchema,
    DestinationDetailSchema,
    DestinationSchema,
    MockDestinationRecord,
    SpotSchema,
)

ORIGIN_COORDS: dict[str, dict[str, float]] = {
    "서울": {"x": 28, "y": 25},
    "부산": {"x": 70, "y": 85},
    "대구": {"x": 58, "y": 62},
    "광주": {"x": 25, "y": 80},
    "대전": {"x": 38, "y": 50},
    "제주": {"x": 25, "y": 95},
}

MOCK_DESTINATIONS: list[MockDestinationRecord] = [
    MockDestinationRecord(
        destination=DestinationSchema(
            id="gangneung",
            title="강릉",
            region="강원도",
            address="강원특별자치도 강릉시",
            imageUrl="https://images.unsplash.com/photo-1542240976-90426fe4f8b2?auto=format&fit=crop&q=80&w=800",
            themes=["바다", "감성"],
            summary="푸른 파도와 커피 향기가 가득한 낭만적인 해변 도시입니다.",
            reasonBadges=["바다 감성", "당일치기 가능"],
            emojiHints=["🌊", "☕", "🏖️", "🚶"],
            dataSource="MOCK_FALLBACK",
            detail=DestinationDetailSchema(
                mapQuery="강릉시",
                estimatedTravelTime="서울역 기준 KTX 2시간",
                canReturnToday=True,
                recommendedStayTime="6~8시간",
                nearbySpots=[
                    SpotSchema(name="안목해변 커피거리", description="바다 정취를 느끼며 즐기는 스페셜티 커피"),
                    SpotSchema(name="강문해변", description="아기자기한 포토존이 가득한 감성 해변"),
                    SpotSchema(name="스테이 인터뷰", description="SNS에서 핫한 바다 전망 인생샷 명소"),
                ],
                dayTripCourse=["강릉역 도착", "안목해변 카페 투어", "중앙시장 먹거리", "강문해변 산책", "강릉역 출발"],
                overnightCourse=["1일차: 경포대 & 오죽헌", "2일차: 소금강 계곡 & 정동진"],
                accommodations=[
                    AccommodationSchema(name="세인트존스 호텔", type="호텔", priceRange="15~30만원"),
                    AccommodationSchema(name="강릉 게스트하우스", type="게스트하우스", priceRange="3~6만원"),
                ],
            ),
        ),
        coords={"x": 55, "y": 18},
        travel_types=["day", "overnight"],
        requires_flight=False,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="jeju",
            title="제주",
            region="제주특별자치도",
            address="제주특별자치도 제주시",
            imageUrl=None,
            themes=["자연"],
            summary="사계절 내내 숨멎게 하는 에메랄드빛 바다와 한라산의 경이로움.",
            reasonBadges=["힐링 자연", "항공 이동"],
            emojiHints=["🌴", "🍊", "🧊", "🌋"],
            dataSource="MOCK_FALLBACK",
            detail=DestinationDetailSchema(
                mapQuery="제주시",
                estimatedTravelTime="김포공항 기준 비행기 1시간 10분",
                canReturnToday=False,
                recommendedStayTime="2박 3일 이상",
                nearbySpots=[
                    SpotSchema(name="협재해수욕장", description="에메랄드빛 바다 뒤로 비양도가 보이는 절경"),
                    SpotSchema(name="사려니숲길", description="삼나무 가득한 숲에서 즐기는 피톤치드 샤워"),
                    SpotSchema(name="성산일출봉", description="유네스코 세계자연유산, 장엄한 일출 명소"),
                ],
                overnightCourse=["1일차: 서쪽 해안도로 드라이브", "2일차: 중문 단지 & 서귀포", "3일차: 성산일출봉 & 우도"],
                accommodations=[
                    AccommodationSchema(name="신라호텔 제주", type="리조트", priceRange="40~80만원"),
                    AccommodationSchema(name="제주 감성 숙소", type="독채펜션", priceRange="20~40만원"),
                ],
            ),
        ),
        coords={"x": 25, "y": 95},
        travel_types=["overnight"],
        requires_flight=True,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="jeonju",
            title="전주",
            region="전라북도",
            address="전북특별자치도 전주시",
            imageUrl="https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&q=80&w=800",
            themes=["맛집", "문화"],
            summary="한옥의 멋과 깊은 손맛이 살아있는 한국 대표 미식 도시.",
            reasonBadges=["전통 먹방", "당일치기 가능"],
            emojiHints=["🍱", "🏮", "🥢", "🍚"],
            dataSource="MOCK_FALLBACK",
            detail=DestinationDetailSchema(
                mapQuery="전주 한옥마을",
                estimatedTravelTime="용산역 기준 KTX 1시간 40분",
                canReturnToday=True,
                recommendedStayTime="5~7시간",
                nearbySpots=[
                    SpotSchema(name="전주 한옥마을", description="700여 채의 한옥이 모여있는 한국 최대 한옥촌"),
                    SpotSchema(name="남부시장", description="전주 피순대와 콩나물국밥의 성지"),
                    SpotSchema(name="경기전", description="태조 이성계의 어진을 모신 역사적 공간"),
                ],
                dayTripCourse=["전주역 도착", "한옥마을 산책", "남부시장 점심", "객리단길 카페", "전주역 출발"],
            ),
        ),
        coords={"x": 32, "y": 65},
        travel_types=["day", "overnight"],
        requires_flight=False,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="danyang",
            title="단양",
            region="충청북도",
            address="충청북도 단양군",
            imageUrl="https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=800",
            themes=["액티비티", "자연"],
            summary="패러글라이딩의 성지이자 남한강의 절경을 품은 액티비티 천국.",
            reasonBadges=["스릴 산책", "당일치기 가능"],
            emojiHints=["🪂", "⛰️", "🌉", "🥾"],
            dataSource="MOCK_FALLBACK",
            detail=DestinationDetailSchema(
                mapQuery="단양군",
                estimatedTravelTime="청량리역 기준 KTX 1시간 20분",
                canReturnToday=True,
                recommendedStayTime="6~9시간",
                nearbySpots=[
                    SpotSchema(name="카페 산", description="패러글라이딩 활공장에서 즐기는 커피와 절경"),
                    SpotSchema(name="만천하 스카이워크", description="남한강 위 공중을 걷는 아찔한 경험"),
                    SpotSchema(name="도담삼봉", description="강 한가운데 솟은 세 가지 봉우리"),
                ],
                dayTripCourse=["단양역 도착", "만천하 스카이워크", "점심(마늘정식)", "패러글라이딩 체험", "단양역 출발"],
            ),
        ),
        coords={"x": 48, "y": 35},
        travel_types=["day", "overnight"],
        requires_flight=False,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="busan",
            title="부산",
            region="경상남도",
            address="부산광역시",
            imageUrl="https://images.unsplash.com/photo-1590603740183-980e7f98e1ca?auto=format&fit=crop&q=80&w=800",
            themes=["바다", "감성"],
            summary="화려한 빌딩 숲과 시원한 바다가 조화를 이루는 제2의 수도.",
            reasonBadges=["바다 야경", "1박 2일 추천"],
            emojiHints=["🎡", "🌉", "🐟", "🚆"],
            dataSource="MOCK_FALLBACK",
            detail=DestinationDetailSchema(
                mapQuery="부산광역시",
                estimatedTravelTime="서울역 기준 KTX 2시간 30분",
                canReturnToday=True,
                recommendedStayTime="1박 2일 이상",
                nearbySpots=[
                    SpotSchema(name="광안리 해수욕장", description="드론 쇼와 광안대교 야경이 어우러진 비치"),
                    SpotSchema(name="해운대 엘시티", description="부산 최고의 전경을 자랑하는 99층 전망대"),
                    SpotSchema(name="흰여울문화마을", description="바다 절벽 위 골목길에서 느끼는 산토리니 감성"),
                ],
                overnightCourse=["1일차: 해운대 & 광안리 야경", "2일차: 영도 흰여울마을 & 남포동"],
                accommodations=[
                    AccommodationSchema(name="파라다이스 호텔 부산", type="호텔", priceRange="30~60만원"),
                    AccommodationSchema(name="해운대 라비드아틀란", type="호텔", priceRange="10~20만원"),
                ],
            ),
        ),
        coords={"x": 70, "y": 85},
        travel_types=["overnight"],
        requires_flight=False,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="gyeongju",
            title="경주",
            region="경상북도",
            address="경상북도 경주시",
            imageUrl="https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=800",
            themes=["문화", "자연"],
            summary="천년의 역사가 밤이 되면 더욱 아름답게 빛나는 노천 박물관.",
            reasonBadges=["역사 야경", "당일치기 가능"],
            emojiHints=["🌙", "🏺", "👑", "🏯"],
            dataSource="MOCK_FALLBACK",
            detail=DestinationDetailSchema(
                mapQuery="경주시",
                estimatedTravelTime="서울역 기준 KTX 2시간",
                canReturnToday=True,
                recommendedStayTime="7~10시간",
                nearbySpots=[
                    SpotSchema(name="동궁과 월지", description="신라의 궁궐터, 환상적인 야경 반영 명소"),
                    SpotSchema(name="황리단길", description="전통 가옥과 힙한 카페가 공존하는 핫플레이스"),
                    SpotSchema(name="교촌마을", description="경주 최부자댁의 역사가 깃든 한옥 마을"),
                ],
                dayTripCourse=["경주역 도착", "불국사", "황리단길 점심", "대릉원 & 동궁과 월지 야경", "경주역 출발"],
            ),
        ),
        coords={"x": 72, "y": 65},
        travel_types=["day", "overnight"],
        requires_flight=False,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="paju",
            title="파주",
            region="경기도",
            address="경기도 파주시",
            imageUrl="https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&q=80&w=800",
            themes=["문화", "감성"],
            summary="예술가들의 숨결과 평화의 기운이 감도는 복합 문화 도시.",
            reasonBadges=["독서 문화", "당일치기"],
            emojiHints=["📚", "🎨", "🏰", "🕊️"],
            dataSource="MOCK_FALLBACK",
            detail=DestinationDetailSchema(
                mapQuery="파주시",
                estimatedTravelTime="서울 중심 기준 차로 1시간",
                canReturnToday=True,
                recommendedStayTime="5~8시간",
                nearbySpots=[
                    SpotSchema(name="파주 출판도시", description="건축미 넘치는 도서관과 북카페가 가득한 책의 마을"),
                    SpotSchema(name="헤이리 예술마을", description="다양한 갤러리와 체험 시설이 있는 예술가 공동체"),
                    SpotSchema(name="임진각 평화누리공원", description="넓은 잔디 언덕 위로 많은 바람개비가 돌아가는 곳"),
                ],
                dayTripCourse=["파주 출발", "출판도시 지혜의 숲", "헤이리 마늘빵 맛집", "임진각 노을 감상", "귀가"],
            ),
        ),
        coords={"x": 22, "y": 15},
        travel_types=["day"],
        requires_flight=False,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="sokcho",
            title="속초",
            region="강원도",
            address="강원특별자치도 속초시",
            imageUrl="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
            themes=["바다", "자연"],
            summary="설악산과 동해가 만나는 푸른 해변 휴양 도시.",
            reasonBadges=["바다 힐링", "당일치기 가능"],
            emojiHints=["🌊", "🏔️", "🦑", "🌅"],
            dataSource="MOCK_FALLBACK",
            latitude=38.2070,
            longitude=128.5918,
            detail=DestinationDetailSchema(
                mapQuery="속초시",
                estimatedTravelTime="서울 기준 고속버스 2시간 30분",
                canReturnToday=True,
                recommendedStayTime="6~8시간",
                nearbySpots=[
                    SpotSchema(name="속초 해변", description="도심과 가까운 대표 해변"),
                    SpotSchema(name="아바이마을", description="오징어순대와 감성 골목"),
                    SpotSchema(name="설악산 국립공원", description="사계절 아름다운 산행 코스"),
                ],
                dayTripCourse=["속초 도착", "해변 산책", "중앙시장", "아바이마을", "귀가"],
            ),
        ),
        coords={"x": 58, "y": 12},
        travel_types=["day", "overnight"],
        requires_flight=False,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="yeosu",
            title="여수",
            region="전라남도",
            address="전라남도 여수시",
            imageUrl="https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&q=80&w=800",
            themes=["바다", "맛집"],
            summary="낭만적인 해안 도로와 신선한 해산물이 가득한 항구 도시.",
            reasonBadges=["해안 드라이브", "1박 2일 추천"],
            emojiHints=["🌉", "🦐", "🚢", "🌅"],
            dataSource="MOCK_FALLBACK",
            latitude=34.7604,
            longitude=127.6622,
            detail=DestinationDetailSchema(
                mapQuery="여수시",
                estimatedTravelTime="서울 기준 KTX 3시간",
                canReturnToday=True,
                recommendedStayTime="1박 2일",
                nearbySpots=[
                    SpotSchema(name="오동도", description="소녀상과 해안 산책로"),
                    SpotSchema(name="여수 밤바다", description="야경 명소"),
                    SpotSchema(name="돌산대교", description="장대한 해상 다리"),
                ],
                overnightCourse=["1일차: 오동도 & 해상케이블카", "2일차: 돌산대교 & 해산물"],
            ),
        ),
        coords={"x": 42, "y": 92},
        travel_types=["day", "overnight"],
        requires_flight=False,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="tongyeong",
            title="통영",
            region="경상남도",
            address="경상남도 통영시",
            imageUrl="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80&w=800",
            themes=["바다", "액티비티"],
            summary="섬과 바다가 어우러진 남해의 대표 해양 관광 도시.",
            reasonBadges=["섬 투어", "1박 2일 추천"],
            emojiHints=["⛵", "🏝️", "🦪", "🌊"],
            dataSource="MOCK_FALLBACK",
            latitude=34.8544,
            longitude=128.4331,
            detail=DestinationDetailSchema(
                mapQuery="통영시",
                estimatedTravelTime="서울 기준 KTX 3시간",
                canReturnToday=False,
                recommendedStayTime="1박 2일",
                nearbySpots=[
                    SpotSchema(name="동피랑 벽화마을", description="알록달록 벽화 골목"),
                    SpotSchema(name="한려수도", description="아름다운 다도해 뷰"),
                    SpotSchema(name="루지 통영", description="스릴 넘치는 액티비티"),
                ],
                overnightCourse=["1일차: 동피랑 & 케이블카", "2일차: 섬 투어"],
            ),
        ),
        coords={"x": 62, "y": 90},
        travel_types=["overnight"],
        requires_flight=False,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="chuncheon",
            title="춘천",
            region="강원도",
            address="강원특별자치도 춘천시",
            imageUrl="https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=800",
            themes=["자연", "감성"],
            summary="소양호와 남이섬이 있는 감성 호수 도시.",
            reasonBadges=["호수 감성", "당일치기 가능"],
            emojiHints=["🏞️", "🚲", "🌲", "☕"],
            dataSource="MOCK_FALLBACK",
            latitude=37.8813,
            longitude=127.7298,
            detail=DestinationDetailSchema(
                mapQuery="춘천시",
                estimatedTravelTime="청량리역 기준 ITX 1시간 20분",
                canReturnToday=True,
                recommendedStayTime="5~7시간",
                nearbySpots=[
                    SpotSchema(name="남이섬", description="가을 단풍과 자작나무길"),
                    SpotSchema(name="소양강스카이워크", description="호수 위 전망대"),
                    SpotSchema(name="춘천 닭갈비골목", description="대표 먹거리"),
                ],
                dayTripCourse=["춘천역 도착", "남이섬", "닭갈비 점심", "소양호", "귀가"],
            ),
        ),
        coords={"x": 42, "y": 22},
        travel_types=["day", "overnight"],
        requires_flight=False,
    ),
    MockDestinationRecord(
        destination=DestinationSchema(
            id="incheon",
            title="인천",
            region="인천광역시",
            address="인천광역시 중구",
            imageUrl="https://images.unsplash.com/photo-1519046904884-53103b34f206?auto=format&fit=crop&q=80&w=800",
            themes=["바다", "문화"],
            summary="월미도와 차이나타운이 있는 서해 게이트웨이.",
            reasonBadges=["근교 바다", "당일치기"],
            emojiHints=["🌊", "🎡", "🏮", "✈️"],
            dataSource="MOCK_FALLBACK",
            latitude=37.4563,
            longitude=126.7052,
            detail=DestinationDetailSchema(
                mapQuery="인천 차이나타운",
                estimatedTravelTime="서울 기준 지하철 1시간",
                canReturnToday=True,
                recommendedStayTime="4~6시간",
                nearbySpots=[
                    SpotSchema(name="월미도", description="해상 놀이공원과 해변"),
                    SpotSchema(name="인천 차이나타운", description="이국적인 거리"),
                    SpotSchema(name="송도 센트럴파크", description="현대적인 해안 공원"),
                ],
                dayTripCourse=["인천역", "차이나타운", "월미도", "저녁 해변", "귀가"],
            ),
        ),
        coords={"x": 18, "y": 28},
        travel_types=["day"],
        requires_flight=False,
    ),
]
